tc-component injection (Magic mode)
sfeir-open-source/talk-control pull request #112
Opened 2020-11-30 13:53 UTC by tarik-irhboula

resolve #50

2021-01-13 17:34 UTC, jefBinomed requested changes
Quelques remarques de nommage, pas mal d'explication pour bien comprendre ce qui est fait et sinon, ce qui serait top c'est d'avoir une sorte d'explication qqe part soit en schéma, soit en texte du mécanisme du mode magic :) car si j'avais pas bossé dessus, j'aurais pas tout compris :)

2021-01-13 17:34 UTC, jefBinomed commented on src/client/web-components/url-form/url-form.js
> -        super.firstUpdated();
pourquoi supprimer l'update ?

2021-01-13 17:34 UTC, jefBinomed commented on src/client/web-components/view-selector/view-selector.js
> -        super.firstUpdated();
pourquoi supprimer l'update ?

2021-01-13 17:34 UTC, jefBinomed commented on src/server/controllers/patcher.controller.js
> +    res.cookie('tc-presentation-url', presentationUrl.href);
c'est quoi l'idée déjà ? de passer par des cookies pour faire quoi ?
Ne risque-t-on pas d'être bloqué avec toutes les politiques anti-cookies des navigateurs ?

2021-01-13 17:34 UTC, jefBinomed commented on src/server/controllers/patcher.controller.js
> +    return html.replace('<head>', `<head><base href="${serverUrl}/proxy/"/>`);
comment on gère le cas où la page a déjà un <base href> ? il est obligatoire ?

2021-01-13 17:34 UTC, jefBinomed commented on config/plugins.json
> -        "path": "@plugins/input/keyboard/index.js",
tu diras si je me trompes @gildas2k  mais je crois que c'est path sont indispensables

2021-01-13 17:34 UTC, jefBinomed commented on src/server/engines/revealjs-server-engine.js
> -    constructor() {
je crois que c'est supprimé de façon un peu brute.... non ? @gildas2k  on a besoin de tout ça non ?

2021-01-13 17:34 UTC, jefBinomed commented on src/server/tc-server.js
> -        this.eventBusServer.onMultiple(CONTROLLER_SERVER_CHANNEL, 'getPlugins', socket => {
je retrouve pas les parties correspondantes ailleurs... @gildas2k  toi qui a bossé sur l'initialisation des plugins, tu peux checker ce code ?

2021-01-13 17:34 UTC, jefBinomed commented on src/common/event-bus/event-bus-resolver.js
> -export const UNKNOWN_CHANNEL = 'Unknown channel';
Il est géré où le UNKNOWN_CHANNEL ensuite ?

2021-01-13 17:34 UTC, jefBinomed commented on src/common/event-bus/event-bus-resolver.js
> +export const Channels = {
J'avoue que je vois pas trop l'intérêt versus ce qu'on avait avant

2021-01-13 17:34 UTC, jefBinomed commented on src/server/controllers/patcher.controller.js
> +function fixHtmlDocument(html) {
juste pour ma culture générale, c'est quoi les cas où on rencontre des documents HTML sans ces balises ?

2021-06-29 09:26 UTC, gildas2k commented on src/client/web-components/magic-info/magic-info.js
> +                    <li>Use of an Iframe pointing to an external website</li>
iframe

2021-06-29 09:26 UTC, gildas2k commented on src/client/web-components/magic-info/magic-info.js
> +                    If you are in one of those cases, we encourage you to test the "magic" before.<br/>
"magic mode" at first.

2021-06-29 09:26 UTC, gildas2k commented on src/client/web-components/magic-info/magic-info.js
> +                    If something is not working, please refer to manually process.<br/>
please refer to the manual process

2021-06-29 09:26 UTC, gildas2k commented on src/client/web-components/magic-info/magic-info.js
> +                    To use the magic, please click here :
To use the magic mode

2021-06-29 09:26 UTC, gildas2k commented on src/client/web-components/magic-info/magic-info.js
> +                    <button id="doMagic" class="is-size-4">Do the magic 🧙‍♀️</button>
doMagic => initMagicMode
Do the magic => Use magic mode

2021-06-29 09:26 UTC, gildas2k commented on src/client/web-components/magic-info/magic-info.js
> +                <h2>Or do it manually</h2>
Or to do it manually

2021-06-29 09:26 UTC, gildas2k commented on src/client/web-components/magic-info/magic-info.js
> +class MagicInfo extends LitElement {
Il faudrait trouver un meilleur nom que MagicInfo.
Propositions : MagicModeTutorialComponent / MagicModeMessageComponent / MagicModeTriggerComponent
(renommer le fichier en rapport)

2021-06-29 09:26 UTC, gildas2k commented on src/client/web-components/notes/notes.js
> +    addNotes(notes) {
Qu'est-ce que ça apporte de ne plus passer par le postMessage en fait ?
On ne risque pas de tenter un getElementById sur un composant qui n'est pas encore dans le shadowroot ?

2021-06-29 09:26 UTC, gildas2k commented on src/client/web-components/timer/timer.js
>          this.timerElement = this.shadowRoot.querySelector('#timer');
Même remarque/question que pour NotesTCComponent pour moi.
Quel est le gain de ne pas passer par postMessage ?

2021-06-29 09:26 UTC, gildas2k commented on src/server/engines/revealjs-server-engine.js
> -    constructor() {
Oui, on devrait garder

2021-06-29 09:26 UTC, gildas2k commented on src/server/tc-server.js
> -        this.eventBusServer.onMultiple(CONTROLLER_SERVER_CHANNEL, 'getPlugins', socket => {
Il y a un broadcast de getPlugins de tc-controller vers tc-server qui a sauté.

2021-06-29 09:26 UTC, gildas2k commented on src/server/tc-server.js
> -        this.eventBusServer.onMultiple(CONTROLLER_SERVER_CHANNEL, 'getPlugins', socket => {
Il n'a plus l'air d'être utile car il y a un broadcast de pluginsList dans tc-server. C'est ce qui était faire par getPlugins auparavant.

2021-07-01 12:29 UTC, gildas2k commented on src/client/web-components/timer/timer.js
> +class Timer extends LitElement {
J'ai remis TimerComponent.

2021-07-01 12:30 UTC, gildas2k commented on src/client/web-components/notes/notes.js
> +class Notes extends LitElement {
J'ai remis NotesComponent.

2021-07-01 12:36 UTC, gildas2k commented on src/client/web-components/menu-plugins/menu-plugins.js
> -    constructor() {
J'ai remis et initialisé itemTitle à ''

2021-07-01 12:40 UTC, gildas2k commented on src/client/web-components/menu-plugins/menu-plugins.js
> +    addItemToMenu(itemTitle) {
Cette méthode doit bien ne pas avoir de '_' car ce n'est pas une méthode privée.

2021-07-01 12:40 UTC, gildas2k commented on src/client/web-components/menu-plugins/menu-plugins.js
> +    showMenu() {
Idem, c'est bien de retirer le '_', cette méthode est appelée dans un autre fichier que menu-plugins.

2021-07-01 12:43 UTC, gildas2k commented on src/common/event-bus/event-bus-component.js
> +        this.channel = EventBusResolver.channel(Channels.CONTROLLER_COMPONENT);
J'ai renommé this.channel en :
- this.controllerComponentChannel pour toutes les classes qui héritent de EventBusComponent
- this.controllerServerChannel dans tc-server.js

2021-07-01 12:44 UTC, gildas2k commented on src/client/tc-component/tc-component.js
> +        this.channel.on('ping', () => this.channel.broadcast('pong'));
Cf mon commentaire sur event-bus-component => renommé en controllerComponentChannel

2021-07-01 12:58 UTC, gildas2k commented on src/client/web-components/clock/clock.js
> +class Clock extends LitElement {
J'ai remis ClockComponent.

2021-07-01 12:59 UTC, gildas2k commented on .huskyrc.js
> +        "pre-commit": "npm run lint && git add .",
Je l'ai retiré, ça créait des pb lors des commits unitaires

2021-07-01 13:11 UTC, gildas2k commented on src/client/web-components/menu-plugins/menu-plugins-tc-component.js
> +        this.channel.on('deactivatePlugin', () => this.menuPlugins.showMenu());
A voir en soirée beer/commit

2021-07-01 13:11 UTC, gildas2k commented on src/client/web-components/menu-plugins/menu-plugins.js
> +        this.menuPluginsTcComponent = new MenuPluginsTCComponent(this);
A voir en soirée beer/commit

2021-07-01 13:13 UTC, gildas2k commented on src/client/web-components/notes/notes.js
> +    addNotes(notes) {
A voir en soirée beer/commit

2021-07-01 13:13 UTC, gildas2k commented on src/client/web-components/timer/timer.js
>          this.timerElement = this.shadowRoot.querySelector('#timer');
A voir en soirée beer/commit

2021-07-01 13:13 UTC, gildas2k commented on src/common/event-bus/event-bus-resolver.js
> +export class EventBusProxy extends EventBus {
Done

2021-07-01 13:13 UTC, gildas2k commented on src/client/tc-controller/tc-controller.js
> +        const slideCount = { loading: 0, loaded: 0 };
A voir en soirée beer/commit

2021-07-01 13:15 UTC, gildas2k commented on src/client/web-components/slide-view/slide-view-tc-component.js
> +        this.channel.broadcast('slideLoaded');
On avait on loadPresentation, donc j'ai mis presentationLoading et presentationLoaded.

2021-07-01 13:15 UTC, gildas2k commented on src/client/tc-controller/tc-controller.js
> -        this.eventBusController.broadcast(CONTROLLER_COMPONENT_CHANNEL, 'init');
A voir en soirée beer/commit

2021-07-01 13:15 UTC, gildas2k commented on src/client/web-components/slide-view/slide-view.js
> +        if (this.focus) {
A voir en soirée beer/commit

2021-07-01 13:15 UTC, gildas2k commented on src/client/tc-controller/tc-controller.js
> -    forwardEvents() {
A voir en soirée beer/commit

2021-07-01 13:16 UTC, gildas2k commented on src/client/tc-controller/tc-controller.js
> +    _checkHealthPresentation(timeout) {
J'ai mis _checkTCClientPresence dans l'un de mes derniers commits.

2021-07-01 13:17 UTC, gildas2k commented on src/client/web-components/magic-info/magic-info.js
> +    doMagic() {
A voir en soirée beer/commit

2021-07-01 13:17 UTC, gildas2k commented on src/client/web-components/menu-navigation/menu-navigation.js
> -        super.firstUpdated();
A voir en soirée beer/commit

2021-07-01 13:17 UTC, gildas2k commented on src/client/web-components/url-form/url-form.js
> -        super.firstUpdated();
A voir en soirée beer/commit

2021-07-01 13:18 UTC, gildas2k commented on src/client/web-components/view-selector/view-selector.js
> -        super.firstUpdated();
A voir en soirée beer/commit

2021-07-01 13:18 UTC, gildas2k commented on src/server/controllers/patcher.controller.js
> +    res.cookie('tc-presentation-url', presentationUrl.href);
A voir en soirée beer/commit

2021-07-01 13:18 UTC, gildas2k commented on src/server/controllers/patcher.controller.js
> +    return html.replace('<head>', `<head><base href="${serverUrl}/proxy/"/>`);
A voir en soirée beer/commit

2021-07-01 13:19 UTC, gildas2k commented on src/server/engines/revealjs-server-engine.js
> -    constructor() {
A voir en soirée beer/commit

2021-07-01 13:20 UTC, gildas2k commented on src/common/event-bus/event-bus-resolver.js
> -export const UNKNOWN_CHANNEL = 'Unknown channel';
Il n'est plus utilisé, je ne le trouve pas dans le code.
Il servait à quoi, tu te souviens ?

2021-07-01 13:21 UTC, gildas2k commented on src/common/event-bus/event-bus-resolver.js
> +export const Channels = {
A voir en soirée beer/commit

2021-07-01 13:30 UTC, gildas2k commented on src/server/tc-server.js
> +        this.channel = EventBusResolver.channel(Channels.CONTROLLER_SERVER, { server });
Voir mon commentaire sur event-bus-component.js

2021-07-01 13:30 UTC, gildas2k commented on src/client/web-components/remote-control/remote-control.js
> -        super.firstUpdated();
A voir en soirée beer/commit

2021-07-01 13:30 UTC, gildas2k commented on src/client/web-components/slide-view/slide-view.js
> -        super.firstUpdated();
A voir en soirée beer/commit

2021-07-08 09:06 UTC, jefBinomed commented on src/common/event-bus/event-bus-resolver.js
> -export const UNKNOWN_CHANNEL = 'Unknown channel';
non c'était peut être un truc en mode, un jour on verra bien , on aura un channel qu'on connait pas :D. Mais en vrai, je pense que ça sert à rien :D

2021-07-08 09:08 UTC, jefBinomed commented on package.json
> +        "tc-server": "npx nodemon --exec \"babel-node --ignore 'nothing'\" src/server/index.js",
Alors oui mais Tarik m'avait expliqué qu'il n'avait pas trouvé mieux pour contourner le pb.... Donc on va se trimbaler cette dette en effet...

2021-10-01 22:24 UTC, jefBinomed approved these changes

2021-10-01 22:38 UTC, merged